# Generated by Django 3.2.16 on 2023-02-01 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_userinformation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInformation',
        ),
    ]
