# Generated by Django 3.2.16 on 2023-02-12 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Main', '0003_delete_userinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('fuelType', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('fuelPrice', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('frequency', models.IntegerField()),
                ('distance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Main.user')),
                ('mileage', models.FloatField()),
                ('trip', models.ManyToManyField(to='Car.Trip')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('spec', models.CharField(max_length=255)),
                ('currentPrice', models.FloatField(null=True)),
                ('depreciation', models.FloatField(null=True)),
                ('downPayment', models.FloatField(null=True)),
                ('installment', models.FloatField(null=True)),
                ('COE', models.FloatField(null=True)),
                ('roadTax', models.FloatField(null=True)),
                ('OMV', models.FloatField(null=True)),
                ('ARF', models.FloatField(null=True)),
                ('fuelEconomy', models.FloatField(null=True)),
                ('fuelType', models.CharField(max_length=255)),
                ('COEIncl', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'unique_together': {('make', 'model', 'spec')},
            },
        ),
    ]
