# Generated by Django 3.2.16 on 2023-02-12 13:32

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='car',
            managers=[
                ('car_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
