# Generated by Django 3.2.16 on 2023-02-12 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0003_rename_trips_usertrip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertrip',
            old_name='trip',
            new_name='trips',
        ),
    ]
