# Generated by Django 3.2.16 on 2023-02-12 16:34

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0004_rename_trip_usertrip_trips'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='trip',
            managers=[
                ('trip_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='usertrip',
            managers=[
                ('user_trip_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='usertrip',
            old_name='User',
            new_name='user',
        ),
    ]
