# Generated by Django 3.2.16 on 2023-02-12 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0005_auto_20230212_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='COEIncl',
            new_name='COE_Incl',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='currentPrice',
            new_name='current_price',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='downPayment',
            new_name='down_payment',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='fuelEconomy',
            new_name='fuel_economy',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='fuelType',
            new_name='fuel_type',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='roadTax',
            new_name='road_tax',
        ),
        migrations.RenameField(
            model_name='fuel',
            old_name='fuelPrice',
            new_name='fuel_price',
        ),
        migrations.RenameField(
            model_name='fuel',
            old_name='fuelType',
            new_name='fuel_type',
        ),
    ]
