# Generated by Django 3.2.16 on 2023-03-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0010_auto_20230302_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertrip',
            name='trips',
            field=models.ManyToManyField(blank=True, to='Car.Trip'),
        ),
    ]
