# Generated by Django 3.2.16 on 2023-03-16 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0012_auto_20230316_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='destination_latitude',
            new_name='destination_lat',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='destination_longitude',
            new_name='destination_long',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='source_latitude',
            new_name='source_lat',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='source_longitude',
            new_name='source_long',
        ),
    ]
