# Generated by Django 3.2.16 on 2023-03-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0013_auto_20230316_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='destination_lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination_long',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='source_lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='source_long',
            field=models.FloatField(),
        ),
    ]
