# Generated by Django 3.2.16 on 2023-02-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0005_auto_20230226_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='month',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget',
            name='year',
            field=models.PositiveIntegerField(default=2023),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('user', 'category', 'year', 'month'), name='unique_user_budget_by_date'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(check=models.Q(('year__range', (1990, 2100))), name='budget_budget_year_range'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(check=models.Q(('year__range', (1, 12))), name='budget_budget_month_range'),
        ),
    ]
