# Generated by Django 3.2.16 on 2023-02-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0007_remove_budget_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='budget',
            name='budget_budget_month_range',
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(check=models.Q(('month__range', (1, 12))), name='budget_budget_month_range'),
        ),
    ]
