# Generated by Django 3.2.16 on 2023-02-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0008_auto_20230226_0832'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(check=models.Q(('limit__gte', 0.0), ('limit__lte', 100000000)), name='budget_budget_limit_range'),
        ),
    ]
