# Generated by Django 3.2.16 on 2023-02-28 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0010_auto_20230226_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Budget.category'),
            preserve_default=False,
        ),
    ]
