# Generated by Django 3.2.16 on 2023-02-19 04:01

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0002_auto_20230211_0232'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='housinguserdata',
            managers=[
                ('housing_user_data_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='resaleflatprice',
            managers=[
                ('resale_flat_price_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
