ANNUAL_INTEREST_RATE = 0.026
LOAN_PERIOD = 25
HDB_DOWN_PAYMENT_RATE = 0.15
MAX_LTV_RATE = 0.8


#Location and property types
LOCATIONS_LIST = [
    ("ANG MO KIO","ANG MO KIO"),
    ("BEDOK","BEDOK"),
    ("BISHAN","BISHAN"),
    ("BUKIT BATOK","BUKIT BATOK"),
    ("BUKIT MERAH","BUKIT MERAH"),
    ("BUKIT PANJANG","BUKIT PANJANG"),
    ("BUKIT TIMAH","BUKIT TIMAH"),
    ("CENTRAL AREA","CENTRAL AREA"),
    ("CHOA CHU KANG","CHOA CHU KANG"),
    ("CLEMENTI","CLEMENTI"),
    ("GEYLANG","GEYLANG"),
    ("HOUGANG","HOUGANG"),
    ("JURONG EAST","JURONG EAST"),
    ("JURONG WEST","JURONG WEST"),
    ("KALLANG/WHAMPOA","KALLANG/WHAMPOA"),
    ("MARINE PARADE","MARINE PARADE"),
    ("PASIR RIS","PASIR RIS"),
    ("PUNGGOL","PUNGGOL"),
    ("QUEENSTOWN","QUEENSTOWN"),
    ("SEMBAWANG","SEMBAWANG"),
    ("SENGKANG","SENGKANG"),
    ("SERANGOON","SERANGOON"),
    ("TAMPINES","TAMPINES"),
    ("TOA PAYOH","TOA PAYOH"),
    ("WOODLANDS","WOODLANDS"),
    ("YISHUN","YISHUN"),
]

PROPERTY_TYPES_LIST = [
    ("1 ROOM","1 ROOM"),
    ("2 ROOM","2 ROOM"),
    ("3 ROOM","3 ROOM"),
    ("4 ROOM","4 ROOM"),
    ("5 ROOM","5 ROOM"),
    ("EXECUTIVE", "EXECUTIVE" ),
    ("MULTI-GENERATION", "MULTI-GENERATION")
]